# Generated by Django 4.1.7 on 2023-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('calendar', models.CharField(max_length=50)),
                ('dateofbirth', models.DateTimeField()),
                ('dateoftime', models.DateTimeField()),
                ('email', models.EmailField(max_length=100)),
                ('pass1', models.CharField(max_length=50)),
                ('pass2', models.CharField(max_length=50)),
            ],
        ),
    ]
