# Generated by Django 4.1.7 on 2023-03-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancer',
            old_name='calendar',
            new_name='calender',
        ),
    ]
