# Generated by Django 4.1.7 on 2023-03-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_name_cancer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancer',
            name='dateofbirth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='dateoftime',
            field=models.CharField(max_length=50),
        ),
    ]
