# Generated by Django 4.1.5 on 2023-06-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_cancer_dateofbirth_alter_cancer_dateoftime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancer',
            old_name='calender',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='cancer',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='cancer',
            name='dateoftime',
        ),
    ]
