# Generated by Django 4.1.5 on 2023-07-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_admission_form_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admission_Form',
            new_name='BSc_Admission_Form',
        ),
    ]
