# Generated by Django 4.1.5 on 2023-07-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_rename_admission_form_bsc_admission_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsc_admission_form',
            name='image',
            field=models.ImageField(upload_to='BSC-image/'),
        ),
    ]
