# Generated by Django 4.1.5 on 2023-07-01 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_bsc_admission_form_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsc_admission_form',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='BSC-File/'),
            preserve_default=False,
        ),
    ]
