# Generated by Django 4.1.5 on 2023-07-01 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_bsc_admission_form_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsc_admission_form',
            name='branch',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
