# Generated by Django 4.1.5 on 2023-07-02 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_bsc_admission_form_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsc_admission_form',
            name='adhar',
            field=models.FileField(default=django.utils.timezone.now, upload_to='BSc-Adhar-File'),
            preserve_default=False,
        ),
    ]
