# Generated by Django 4.2.5 on 2024-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_student_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='UG_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branches', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('eligibility', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cancer',
        ),
    ]
