# Generated by Django 4.2.5 on 2024-09-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_ug_course_delete_cancer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ug_course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelTable(
            name='ug_course',
            table='ug_courses',
        ),
    ]
