# Generated by Django 4.2.5 on 2024-09-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_alter_ug_course_options_alter_ug_course_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ug_course',
            options={'verbose_name': 'ug_courses'},
        ),
    ]
