# Generated by Django 4.2.5 on 2024-09-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_alter_ug_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ug_course',
            options={},
        ),
    ]
