# Generated by Django 4.2.5 on 2024-09-26 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_alter_ug_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ug_course',
            name='fees',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
