# Generated by Django 4.2.5 on 2024-09-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_ug_course_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsc_admission_form',
            name='adhar',
            field=models.FileField(upload_to='BSc/BSc-Adhar-File'),
        ),
        migrations.AlterField(
            model_name='bsc_admission_form',
            name='file',
            field=models.FileField(upload_to='BSc/BSC-PUC/'),
        ),
        migrations.AlterField(
            model_name='bsc_admission_form',
            name='image',
            field=models.ImageField(upload_to='BSc/BSC-image/'),
        ),
    ]
