# Generated by Django 4.2.5 on 2024-09-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_alter_bsc_admission_form_adhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='user/profile_pics/'),
        ),
    ]
