# Generated by Django 4.2.5 on 2024-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_alter_student_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UG_Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsc', models.FileField(upload_to='bsc_papers')),
            ],
        ),
    ]
