# Generated by Django 4.2.5 on 2024-09-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_ug_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='ug_study',
            name='ba',
            field=models.FileField(default='ba_papers/default_ba.pdf', upload_to='ba_papers'),
        ),
        migrations.AddField(
            model_name='ug_study',
            name='bca',
            field=models.FileField(default='bca_papers/default_bca.pdf', upload_to='bca_papers'),
        ),
        migrations.AddField(
            model_name='ug_study',
            name='bcom',
            field=models.FileField(default='bcom_papers/default_bcom.pdf', upload_to='bcom_papers'),
        ),
    ]
