# Generated by Django 4.2.5 on 2024-10-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0023_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
